export const CALCULATOR_SECTIONS = [
  {
    key: 'trading',
    title: 'Trading',
    subtitle: 'Risk, reward, position sizing, and execution planning.',
    items: [
      {
        id: 'support-resistance',
        title: 'Support & Resistance',
        description: 'Derive key S/R levels from historical price.',
        category: 'trading',
        tags: ['price levels'],
      },
      {
        id: 'win-rate-risk-reward',
        title: 'Win-Rate & Risk-Reward',
        description: 'Plan entries with stop/target and expectancy.',
        category: 'trading',
        tags: ['trade planning'],
      },
      {
        id: 'rr-quick',
        title: 'RR Ratio (Quick)',
        description: 'Fast R:R ratio from stop to target distance.',
        category: 'trading',
        tags: ['trade planning'],
      },
      {
        id: 'risk-reward-break-even',
        title: 'Risk-Reward Ratio Calculator',
        description: 'Find break-even win-rate for a given R:R.',
        category: 'trading',
        tags: ['expectancy'],
      },
      {
        id: 'position-size',
        title: 'Position Size Calculator',
        description: 'Size trades by account risk and stop distance.',
        category: 'trading',
        tags: ['position planning'],
      },
      {
        id: 'stock-dca',
        title: 'Stock Average Calculator',
        description: 'Calculate weighted average buy price across lots.',
        category: 'trading',
        tags: ['position planning'],
      },
      {
        id: 'profit-loss',
        title: 'Profit & Loss (P&L)',
        description: 'Evaluate realized and unrealized trade P&L.',
        category: 'trading',
        tags: ['trading'],
      },
      {
        id: 'fibonacci',
        title: 'Fibonacci Retracement',
        description: 'Compute retracement levels for technical analysis.',
        category: 'trading',
        tags: ['technical analysis'],
      },
      {
        id: 'stop-loss-take-profit',
        title: 'Stop Loss & Take Profit',
        description: 'Compute stop/target values from entry and risk.',
        category: 'trading',
        tags: ['trade planning'],
      },
      {
        id: 'drawdown-capital-recovery',
        title: 'Drawdown & Capital Recovery',
        description: 'Estimate capital required to recover from drawdown.',
        category: 'trading',
        tags: ['risk management'],
      },
      {
        id: 'options-pricing-greeks',
        title: 'Options Pricing & Greeks',
        description: 'Approximate option value and greek sensitivities.',
        category: 'trading',
        tags: ['options'],
      },
      {
        id: 'risk-reward-india',
        title: 'Risk-Reward (India)',
        description: 'Risk-reward helper tailored for Indian market ticks.',
        category: 'trading',
        tags: ['india'],
      },
      {
        id: 'trading-risk-reward',
        title: 'Trading Risk-Reward',
        description: 'Compare risk and reward across multiple setups.',
        category: 'trading',
        tags: ['trading'],
      },
      {
        id: 'risk-to-reward',
        title: 'Risk to Reward',
        description: 'Simple risk to reward ratio calculator.',
        category: 'trading',
        tags: ['trading'],
      },
      {
        id: 'stock-risk-reward',
        title: 'Stock Risk-Reward',
        description: 'Position-level risk-reward for stock trades.',
        category: 'trading',
        tags: ['trading'],
      },
    ],
  },
  {
    key: 'investing',
    title: 'Investing',
    subtitle: 'Returns, valuation, and portfolio analysis tools.',
    items: [
      {
        id: 'cagr',
        title: 'CAGR',
        description: 'Measure annualized investment growth.',
        category: 'investing',
        tags: ['returns'],
      },
      {
        id: 'roi',
        title: 'ROI',
        description: 'Return on investment in absolute terms.',
        category: 'investing',
        tags: ['returns'],
      },
      {
        id: 'npv',
        title: 'NPV',
        description: 'Net present value of discounted cash flows.',
        category: 'investing',
        tags: ['valuation'],
      },
      {
        id: 'irr',
        title: 'IRR',
        description: 'Internal rate of return for investment cash flows.',
        category: 'investing',
        tags: ['valuation'],
      },
      {
        id: 'sharpe-sortino',
        title: 'Sharpe & Sortino Ratios',
        description: 'Risk-adjusted return using Sharpe and Sortino.',
        category: 'investing',
        tags: ['portfolio'],
      },
      {
        id: 'correlation',
        title: 'Correlation & Covariance',
        description: 'Relationship analysis between assets.',
        category: 'investing',
        tags: ['portfolio'],
      },
      {
        id: 'dcf',
        title: 'DCF',
        description: 'Discounted cash flow valuation with terminal value.',
        category: 'investing',
        tags: ['valuation'],
      },
      {
        id: 'portfolio-risk-std',
        title: 'Portfolio Risk (Std Dev)',
        description: 'Portfolio volatility from weighted components.',
        category: 'investing',
        tags: ['portfolio'],
      },
      {
        id: 'efficient-frontier',
        title: 'Efficient Frontier',
        description: 'Optimization helper for asset allocation.',
        category: 'investing',
        tags: ['portfolio'],
      },
      {
        id: 'dividend-pe',
        title: 'Dividend & P/E',
        description: 'Dividend yield and P/E ratio helper.',
        category: 'investing',
        tags: ['valuation'],
      },
    ],
  },
  {
    key: 'personal-finance',
    title: 'Personal Finance',
    subtitle: 'Savings, loans, retirement, and budgeting calculators.',
    items: [
      {
        id: 'emergency-fund',
        title: 'Emergency Fund',
        description: 'Plan safety buffer for unexpected expenses.',
        category: 'personal-finance',
        tags: ['personal finance'],
      },
      {
        id: 'retirement-corpus',
        title: 'Retirement',
        description: 'Estimate retirement corpus and savings path.',
        category: 'personal-finance',
        tags: ['personal finance'],
      },
      {
        id: 'mortgage',
        title: 'Mortgage',
        description: 'Monthly mortgage payments and total interest.',
        category: 'personal-finance',
        tags: ['loans'],
      },
      {
        id: 'emi',
        title: 'EMI Calculator',
        description: 'Loan installment, tenure, and amortization schedule.',
        category: 'personal-finance',
        tags: ['loans'],
      },
      {
        id: 'car-loan',
        title: 'Car Loan EMI Calculator',
        description: 'Vehicle loan EMI with down payment options.',
        category: 'personal-finance',
        tags: ['loans'],
      },
      {
        id: 'home-loan-emi',
        title: 'Home Loan EMI Calculator',
        description: 'Home loan EMI, tenure and full amortization.',
        category: 'personal-finance',
        tags: ['loans'],
      },
      {
        id: 'house-affordability',
        title: 'House Affordability',
        description: 'Estimate home value based on your income.',
        category: 'personal-finance',
        tags: ['loans'],
      },
      {
        id: 'savings-last',
        title: 'How Long Will My Savings Last',
        description: 'Project runway for savings under withdrawals.',
        category: 'personal-finance',
        tags: ['personal finance'],
      },
      {
        id: 'saving-growth',
        title: 'Saving Growth',
        description: 'Visualize savings growth over time.',
        category: 'personal-finance',
        tags: ['personal finance'],
      },
      {
        id: 'save-money-goal',
        title: 'Save Money Calculator',
        description: 'Find monthly savings needed to hit a goal.',
        category: 'personal-finance',
        tags: ['savings'],
      },
      {
        id: 'net-worth',
        title: 'Net Worth Calculator',
        description: 'Calculate current net worth and track trend.',
        category: 'personal-finance',
        tags: ['planning'],
      },
      {
        id: 'college-calculator',
        title: 'College Calculators',
        description: 'Student budget and education planning tools.',
        category: 'personal-finance',
        tags: ['education'],
      },
      {
        id: 'high-yield-savings',
        title: 'High-Yield Savings Calculator',
        description: 'Estimate savings growth with APY and deposits.',
        category: 'personal-finance',
        tags: ['savings'],
      },
      {
        id: 'retirement-savings-pf',
        title: 'Retirement Savings Calculator',
        description: 'Projected retirement corpus and monthly need.',
        category: 'personal-finance',
        tags: ['retirement'],
      },
      {
        id: 'sip',
        title: 'SIP Calculator',
        description: 'Estimate SIP maturity with invested amount.',
        category: 'personal-finance',
        tags: ['mutual funds'],
      },
      {
        id: 'lumpsum',
        title: 'Lumpsum Calculator',
        description: 'Future value estimate for one-time investment.',
        category: 'personal-finance',
        tags: ['mutual funds'],
      },
      {
        id: 'swp',
        title: 'SWP Calculator',
        description: 'Monthly withdrawals and final corpus projection.',
        category: 'personal-finance',
        tags: ['mutual funds'],
      },
      {
        id: 'fd',
        title: 'FD Calculator',
        description: 'Fixed deposit maturity amount and interest.',
        category: 'personal-finance',
        tags: ['deposits'],
      },
      {
        id: 'simple-interest',
        title: 'Simple Interest Calculator',
        description: 'Interest and maturity amount on simple basis.',
        category: 'personal-finance',
        tags: ['deposits'],
      },
      {
        id: 'compound-interest',
        title: 'Compound Interest Calculator',
        description: 'Compound growth from principal and periodic rate.',
        category: 'personal-finance',
        tags: ['deposits'],
      },
      {
        id: 'rd',
        title: 'RD Calculator',
        description: 'Recurring deposit maturity estimate.',
        category: 'personal-finance',
        tags: ['deposits'],
      },
      {
        id: 'mutual-fund-return',
        title: 'Mutual Fund Return Calculator',
        description: 'SIP + lump sum return projection.',
        category: 'personal-finance',
        tags: ['mutual funds'],
      },
      {
        id: 'spending',
        title: 'Spending Calculator',
        description: 'Understand monthly spending breakdown.',
        category: 'personal-finance',
        tags: ['budgeting'],
      },
      {
        id: 'life-insurance',
        title: 'Life Insurance',
        description: 'Estimate required life insurance coverage.',
        category: 'personal-finance',
        tags: ['protection'],
      },
      {
        id: 'property-valuation',
        title: 'Property Valuation',
        description: 'Estimate property value from key inputs.',
        category: 'personal-finance',
        tags: ['real estate'],
      },
      {
        id: 'carpet',
        title: 'Carpet Calculator',
        description: 'Estimate room carpet need and area.',
        category: 'personal-finance',
        tags: ['home improvement'],
      },
      {
        id: '401k-retirement',
        title: '401(k) Retirement Savings',
        description: 'Project 401(k) balance with salary growth and employer match.',
        category: 'personal-finance',
        tags: ['retirement'],
      },
      {
        id: 'fire',
        title: 'Financial Freedom (9-Step)',
        description: 'Target corpus for long-term financial independence.',
        category: 'personal-finance',
        tags: ['financial planning'],
      },
    ],
  },
  {
    key: 'astrology',
    title: 'Astrology',
    subtitle: 'Astrology-based financial and personal insights.',
    items: [
      {
        id: 'astro-longevity',
        title: 'Astrology Longevity',
        description: 'Birth-chart based longevity insights.',
        category: 'astrology',
        tags: ['astrology'],
      },
    ],
  },
];

export const getCalculatorSection = (categoryKey) =>
  CALCULATOR_SECTIONS.find((section) => section.key === categoryKey) || null;
